/*
 * DualControllerSync - Synchronized dual motor control with separate
 * microcontrollers
 *
 * This example demonstrates how to use FastAccelStepper with two independent
 * microcontrollers, each controlling one motor, using a synchronized start
 * signal.
 *
 * Setup:
 * - Two ESP32 microcontrollers
 * - One motor per microcontroller
 * - Hardware sync signal connected to SYNC_PIN on both controllers
 * - Same command list flashed to both controllers
 * - Each controller configured as LEFT or RIGHT motor
 *
 * Hardware connections:
 * - SYNC_PIN: Connect to same sync signal on both controllers (pulled HIGH to
 * start)
 * - STEP_PIN: Connect to stepper driver STEP pin
 * - DIR_PIN: Connect to stepper driver DIR pin
 * - ENABLE_PIN (optional): Connect to stepper driver ENABLE pin
 */

#include <FastAccelStepper.h>

// ============================================================================
// CONFIGURATION - Set this differently for each microcontroller
// ============================================================================

// Define which motor this controller manages
#define MOTOR_LEFT 0
#define MOTOR_RIGHT 1

// **CHANGE THIS FOR EACH MICROCONTROLLER**
#define MOTOR_SIDE MOTOR_LEFT  // or MOTOR_RIGHT for the other controller

// ============================================================================
// PIN CONFIGURATION - Adjust for your hardware
// ============================================================================

#define LEFT_STEP_PIN 19    // GPIO pin for STEP signal
#define LEFT_DIR_PIN 18     // GPIO pin for DIR signal
#define LEFT_ENABLE_PIN 23  // GPIO pin for ENABLE signal

// Microstepping configuration pins
#define MOTOR_MS1 22  // Microstepping MS1 pin
#define MOTOR_MS2 21  // Microstepping MS2 pin

// ============================================================================
// TIMING CONSTRAINTS
// ============================================================================

#define MIN_CMD_TICKS 3200  // ESP32 minimum command duration (200 microseconds)

// ============================================================================
// MOTION COMMAND FORMAT
// ============================================================================

struct MotionCommand {
  int16_t steps_left;       // Steps for LEFT motor
  int16_t steps_right;      // Steps for RIGHT motor
  uint32_t duration_ticks;  // Duration in timer ticks (16MHz for ESP32)
  uint32_t duration_us;     // Duration in microseconds (for debugging/logging)
};

// ============================================================================
// COMMAND LIST - Generated by your external motion planning software
// ============================================================================

// Example: Simple coordinated motion pattern
// LEFT motor does more steps than RIGHT (differential motion)
const MotionCommand motionCommands[] = {
    {15, 11, 1011929, 63246}, {16, 11, 419155, 26197}, {15, 10, 321629, 20102},
    {15, 11, 271146, 16947},  {16, 11, 238884, 14930}, {15, 11, 215968, 13498},

};

const uint16_t COMMAND_COUNT = sizeof(motionCommands) / sizeof(MotionCommand);

// ============================================================================
// GLOBALS
// ============================================================================

FastAccelStepperEngine engine = FastAccelStepperEngine();
FastAccelStepper* stepper = NULL;

// Motion execution state
struct {
  uint16_t commandIndex;  // Current command being executed
  uint32_t drift;         // Accumulated timing drift (in ticks)
  uint64_t totalTime;     // Total accumulated time (in ticks)
  uint32_t totalSteps;    // Total steps executed
  bool completed;         // All commands completed
  bool syncReceived;      // Sync signal received
} motionState = {0, 0, 0, 0, false, false};

// Statistics
struct {
  uint32_t busyCount;      // Number of BUSY returns
  uint32_t emptyCount;     // Number of EMPTY returns (queue ran dry)
  uint32_t notReadyCount;  // Number of DeviceNotReady returns
  uint32_t errorCount;     // Number of errors
  uint32_t maxDrift;       // Maximum drift seen (ticks)
} stats = {0, 0, 0, 0, 0};

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

// Get the steps for this motor from a command
int16_t getStepsForThisMotor(const MotionCommand& cmd) {
#if MOTOR_SIDE == MOTOR_LEFT
  return cmd.steps_left;
#else
  return cmd.steps_right;
#endif
}

// Get motor name string
const char* getMotorName() {
#if MOTOR_SIDE == MOTOR_LEFT
  return "LEFT";
#else
  return "RIGHT";
#endif
}

// Validate a command
bool validateCommand(const MotionCommand& cmd) {
  int16_t steps = getStepsForThisMotor(cmd);

  // Check minimum duration
  if (cmd.duration_ticks < MIN_CMD_TICKS) {
    Serial.printf("ERROR: Command duration too low: %u < %u\n",
                  cmd.duration_ticks, MIN_CMD_TICKS);
    return false;
  }

  // Check ticks × steps constraint (for non-pause commands)
  if (steps != 0) {
    uint32_t ticks_per_step = cmd.duration_ticks / abs(steps);
    if (ticks_per_step * abs(steps) < MIN_CMD_TICKS) {
      Serial.printf("ERROR: ticks × steps < MIN_CMD_TICKS: %u × %d\n",
                    ticks_per_step, abs(steps));
      return false;
    }
  }

  return true;
}

// Wait for serial input to start
void waitForSerialStart() {
  Serial.println("Press any key and hit ENTER to start motion execution...");
  Serial.println();

  // Wait for any serial input
  while (!Serial.available()) {
    delay(10);  // Poll every 10ms
  }

  // Clear the serial buffer
  while (Serial.available()) {
    Serial.read();
  }

  motionState.syncReceived = true;
  Serial.println("Starting motion execution NOW!");
  Serial.println();
}

// Print status (called periodically)
void printStatus() {
  static uint32_t lastPrint = 0;
  uint32_t now = millis();

  if (now - lastPrint >= 1000) {  // Print every 1 second
    lastPrint = now;

    Serial.printf(
        "[%s] Cmd:%u/%u Steps:%lu Time:%luus Drift:%ld Busy:%lu Empty:%lu "
        "NR:%lu Err:%lu\n",
        getMotorName(), motionState.commandIndex, COMMAND_COUNT,
        motionState.totalSteps,
        (uint32_t)(motionState.totalTime / 16),  // Convert ticks to us
        (int32_t)motionState.drift, stats.busyCount, stats.emptyCount,
        stats.notReadyCount, stats.errorCount);
  }
}

// Execute one command from the list
void executeNextCommand() {
  if (motionState.commandIndex >= COMMAND_COUNT) {
    if (!motionState.completed) {
      motionState.completed = true;
      Serial.println("=== All commands completed ===");
      Serial.printf("Total steps: %lu\n", motionState.totalSteps);
      Serial.printf("Total time: %lu us\n",
                    (uint32_t)(motionState.totalTime / 16));
      Serial.printf("Final drift: %ld ticks (%ld us)\n",
                    (int32_t)motionState.drift,
                    (int32_t)motionState.drift / 16);
      Serial.printf("Max drift: %lu ticks (%lu us)\n", stats.maxDrift,
                    stats.maxDrift / 16);
      Serial.printf("Stats - Busy:%lu Empty:%lu NotReady:%lu Errors:%lu\n",
                    stats.busyCount, stats.emptyCount, stats.notReadyCount,
                    stats.errorCount);
    }
    return;
  }

  // Get current command
  const MotionCommand& cmd = motionCommands[motionState.commandIndex];
  int16_t steps = getStepsForThisMotor(cmd);

  // Apply drift compensation
  uint32_t duration = cmd.duration_ticks + motionState.drift;
  uint32_t actual = 0;

  // Execute the timed move
  MoveTimedResultCode rc = stepper->moveTimed(steps, duration, &actual, true);

  switch (rc) {
    case MOVE_TIMED_OK:
      // Command successfully queued
      motionState.drift = duration - actual;
      motionState.totalTime += actual;
      motionState.totalSteps += abs(steps);
      motionState.commandIndex++;

      // Track max drift
      if (abs((int32_t)motionState.drift) > stats.maxDrift) {
        stats.maxDrift = abs((int32_t)motionState.drift);
      }
      break;

    case MOVE_TIMED_EMPTY:
      // Queue ran dry, but command was added
      Serial.printf("WARNING: Queue empty at command %u\n",
                    motionState.commandIndex);
      stats.emptyCount++;

      motionState.drift = duration - actual;
      motionState.totalTime += actual;
      motionState.totalSteps += abs(steps);
      motionState.commandIndex++;

      if (abs((int32_t)motionState.drift) > stats.maxDrift) {
        stats.maxDrift = abs((int32_t)motionState.drift);
      }
      break;

    case MOVE_TIMED_BUSY:
      // Queue doesn't have room, retry next loop
      stats.busyCount++;
      break;

    case MoveTimedResultCode::DeviceNotReady:
      // RMT peripheral still initializing, retry next loop
      // This is normal right after starting the queue
      stats.notReadyCount++;
      delayMicroseconds(10);  // Small delay to let peripheral initialize
      break;

    case MOVE_TIMED_TOO_LARGE_ERROR:
      Serial.printf("ERROR: Command %u too large (steps=%d, duration=%lu)\n",
                    motionState.commandIndex, steps, cmd.duration_ticks);
      stats.errorCount++;
      motionState.commandIndex++;  // Skip this command
      break;

    case MoveTimedResultCode::ErrorTicksTooLow:
      Serial.printf(
          "ERROR: Command %u ticks too low (steps=%d, duration=%lu)\n",
          motionState.commandIndex, steps, cmd.duration_ticks);
      stats.errorCount++;
      motionState.commandIndex++;  // Skip this command
      break;

    default:
      Serial.printf("ERROR: Command %u failed with code: %s\n",
                    motionState.commandIndex, toString(rc));
      stats.errorCount++;
      motionState.commandIndex++;  // Skip this command
      break;
  }
}

// ============================================================================
// ARDUINO SETUP
// ============================================================================

void setup() {
  Serial.begin(115200);
  delay(1000);  // Wait for serial to initialize

  Serial.println("\n\n=================================================");
  Serial.println("FastAccelStepper - Dual Controller Sync Example");
  Serial.println("=================================================");
  Serial.printf("Motor side: %s\n", getMotorName());
  Serial.printf("Command count: %u\n", COMMAND_COUNT);
  Serial.printf("Step pin: %d\n", LEFT_STEP_PIN);
  Serial.printf("Dir pin: %d\n", LEFT_DIR_PIN);
  Serial.printf("Enable pin: %d\n", LEFT_ENABLE_PIN);
  Serial.printf("Microstepping MS1: %d\n", MOTOR_MS1);
  Serial.printf("Microstepping MS2: %d\n", MOTOR_MS2);
  Serial.println("=================================================\n");

  // Configure microstepping pins
  pinMode(MOTOR_MS1, OUTPUT);
  pinMode(MOTOR_MS2, OUTPUT);
  digitalWrite(MOTOR_MS1, LOW);  // Set microstepping mode
  digitalWrite(MOTOR_MS2,
               LOW);  // LOW/LOW = full step or 1/2 step depending on driver
  Serial.println("Microstepping configured (MS1=LOW, MS2=LOW)");

  // Initialize FastAccelStepper engine
  engine.init();
  stepper = engine.stepperConnectToPin(LEFT_STEP_PIN);

  if (!stepper) {
    Serial.println("ERROR: Failed to initialize stepper!");
    while (1) {
      delay(1000);
    }
  }

  // Configure stepper
  stepper->setDirectionPin(LEFT_DIR_PIN);
  stepper->setEnablePin(LEFT_ENABLE_PIN);
  stepper->setAutoEnable(false);  // Manual enable control for better timing

  Serial.println("Stepper initialized successfully.");

  // Manually enable the stepper driver
  stepper->enableOutputs();
  Serial.println("Stepper driver enabled.");

  // Wait for stepper driver to stabilize (important!)
  delay(100);  // 100ms delay for driver to wake up
  Serial.println("Driver stabilization delay complete.");

  // Validate all commands
  Serial.println("Validating command list...");
  bool allValid = true;
  for (uint16_t i = 0; i < COMMAND_COUNT; i++) {
    if (!validateCommand(motionCommands[i])) {
      Serial.printf("ERROR: Command %u failed validation\n", i);
      allValid = false;
    }
  }

  if (!allValid) {
    Serial.println("ERROR: Command validation failed!");
    while (1) {
      delay(1000);
    }
  }
  Serial.println("All commands validated successfully.\n");

  // Pre-fill queue with a longer pause to prevent queue from running dry
  // before the first real command can be added
  Serial.println("Pre-filling queue...");
  stepper->moveTimed(0, TICKS_PER_S / 2, NULL, false);  // 500ms pause, don't start
  Serial.println("Queue pre-filled.\n");

  // Wait for serial input to start
  waitForSerialStart();

  // Start execution when user presses a key
  stepper->moveTimed(0, 0, NULL, true);  // Start the queue NOW

  Serial.println("Motion execution started!\n");
}

// ============================================================================
// ARDUINO LOOP
// ============================================================================

void loop() {
  // Execute commands
  executeNextCommand();

  // Print periodic status
  printStatus();

  // Optional: small delay to prevent tight loop (adjust as needed)
  // delayMicroseconds(100);
}
